
import "./globals.css";
import {ReactLenis} from "@/components/lenis"



export const metadata = {
  title: "KBR - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ReactLenis root>
      <body className="antialiased">{children}</body>
      </ReactLenis>
    </html>
  );
}
