
import "./globals.css";
import {ReactLenis} from "@/components/lenis"
// import {Poppins} from "next/dist/compiled/@next/font/dist/google";
import { Poppins } from 'next/font/google';

export const metadata = {
  title: "KBR - Portfolio",
  description: "Generated by create next app",
};

// Configure Poppins with the weights and styles you need
const poppins = Poppins({
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
    style: ['normal', 'italic'],
    subsets: ['latin'],
    display: 'swap',
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ReactLenis root>
      <body className={`${poppins.className} antialiased`}>{children}</body>
      </ReactLenis>
    </html>
  );
}
